Repository reactphp/stream, pull requests merged in 2024-05, with the labels that each got.

#175 Update to require PHP 7.1+
  .github/workflows/ci.yml
  README.md
  composer.json
  examples/01-http.php
  examples/02-https.php
  examples/91-benchmark-throughput.php
  phpunit.xml.legacy
  src/CompositeStream.php
  src/DuplexResourceStream.php
  src/ReadableResourceStream.php
  src/ReadableStreamInterface.php
  src/ThroughStream.php
  src/Util.php
  src/WritableResourceStream.php
  tests/CompositeStreamTest.php
  tests/DuplexResourceStreamIntegrationTest.php
  tests/DuplexResourceStreamTest.php
  tests/FunctionalInternetTest.php
  tests/ReadableResourceStreamTest.php
  tests/Stub/ReadableStreamStub.php
  tests/TestCase.php
  tests/ThroughStreamTest.php
  tests/UtilTest.php
  tests/WritableResourceStreamTest.php
Labels: BC break

#177 Improve PHP 8.4+ support by avoiding implicitly nullable types
  src/DuplexResourceStream.php
  src/ReadableResourceStream.php
  src/WritableResourceStream.php
Labels: new feature

#179 [1.x] Improve PHP 8.4+ support by avoiding implicitly nullable types
  src/DuplexResourceStream.php
  src/ReadableResourceStream.php
  src/WritableResourceStream.php
  tests/DuplexResourceStreamTest.php
  tests/ReadableResourceStreamTest.php
  tests/WritableResourceStreamTest.php
Labels: new feature

#178 Add native types to public API
  README.md
  src/CompositeStream.php
  src/DuplexResourceStream.php
  src/ReadableResourceStream.php
  src/ReadableStreamInterface.php
  src/ThroughStream.php
  src/Util.php
  src/WritableResourceStream.php
  src/WritableStreamInterface.php
  tests/Stub/ReadableStreamStub.php
  tests/ThroughStreamTest.php
Labels: new feature, BC break
